# Generated by Django 4.2.5 on 2024-02-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upld', '0002_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='contact',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='userName',
            field=models.CharField(),
        ),
    ]
