# Generated by Django 4.2.5 on 2024-02-23 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upld', '0003_alter_userinfo_contact_alter_userinfo_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='contact',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='upiId',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='userName',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('paidAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('splitedAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paidBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purposes_paid', to='upld.userinfo')),
            ],
        ),
    ]
