# Generated by Django 4.2.5 on 2024-02-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upld', '0004_alter_userinfo_contact_alter_userinfo_upiid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purpose',
            name='paidBy',
            field=models.CharField(),
        ),
    ]
