# Generated by Django 4.2.5 on 2024-02-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upld', '0005_alter_purpose_paidby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purpose',
            name='paidBy',
            field=models.CharField(max_length=377),
        ),
    ]
